config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => 'registrations' }
  root to: redirect('users/dashboard')
  get 'users/roulette' => 'users#dashboard'
  post 'users/roulette' => 'users#roulette'
  post 'users/block/:id' => 'users#block'
  post 'users/unblock' => 'users#unblock'
  post 'users/set_threshold' => 'users#set_threshold'
  post 'users/save/:id' => 'users#save'
  get 'users/unblock_all' => 'users#unblock_all'
  get  'users/dashboard' => 'users#dashboard'
  post 'users/dashboard' => 'users#update'
  post 'pantries/update' => 'pantries#update'
  post 'users/delete' => 'users#delete'
  resources :ratings, only: :update
  resources :recipes
  resources :pantries do
    collection {post :sort}
  end

end

app/models/pantry.rb
class Pantry < ActiveRecord::Base
  has_many :pantry_ingredients
  has_many :ingredients, through: :pantry_ingredients
  belongs_to :user
  validates :user_id, presence: true
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  has_and_belongs_to_many :tags, uniq: true
  has_and_belongs_to_many :ingredients, :uniq => true
  has_and_belongs_to_many :blockedrecipelists, :uniq => true, :read_only => true
  has_and_belongs_to_many :users, :uniq => true
  has_many :ratings

  has_attached_file :image, styles: {
    thumb: '100x100>',
    medium: '500x500>',
    large:  '1000x1000>'
  }

  validates :name, presence: true, uniqueness: true
  validates :instructions, presence: true
  validates :prep_time, presence: true
  validates :cook_time, presence: true

  validates_attachment :image, 
  :content_type => { :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"] },
  :size => { :in => 0..2.megabytes }

  def average_rating
    if ratings.size > 0
      return ratings.sum(:score) / ratings.size
    else
      return 0
    end
  end

  def to_s
    name
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_and_belongs_to_many :recipes
  has_one :blockedrecipelist
  has_one :pantry
  before_create :build_pantry
  before_create :build_blockedrecipelist
  validates_associated :blockedrecipelist
  validates_associated :pantry
  has_many :ratings
end

app/controllers/Users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/Users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when omniauth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/Users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/Users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user_controller.rb
class UserController < ApplicationController

  # test
  def new
  end

  def create
  end

  def show
  end

  def edit
  end

  def update
    @user = current_user
    @pantry = @user.pantry
    if params[:commit] == 'Remove Ingredient'
      @ingredient = Ingredient.find(params[:ingredient][:ingredient_id])
      @pantry.ingredients.delete(@ingredient)
      @pantry.save
    elsif params[:commit] == 'Add Ingredient'
      ingredient = Ingredient.where(name: params[:ingredient][:name]).first
      if ingredient && !@pantry.ingredients.exists?(@ingredient)
        @pantry.ingredients << ingredient
        @pantry.save
      elsif !ingredient
        # Probably want to flash message that ingredient couldn't be found
        flash.now[:ingredienterror] = "Sorry, #{params[:ingredient][:name]} is not a valid ingredient"
      end
    end
    render 'dashboard'
  end

  def destroy
  end

  def dashboard
    @user = current_user
    if @user
      @pantry = @user.pantry
    else
      render 'new'
    end
  end

  # list_of_recipe_names is set to a list when they play roulette (can be empty)
  # any time they hit roulette page, force re-query of database
  def roulette
    @list_of_recipe_names = gather_user_recipe_names
    @list_of_recipe_names.shuffle! # randomize names!

    render_appropriate_page(@list_of_recipe_names)
  end

  def block
    @user = current_user

    recipe = Recipe.where({name: params[:name]}).first
    recipe_already_blocked = @user.blockedrecipelist.recipes.where(id: recipe.id).length > 0
    @user.blockedrecipelist.recipes << recipe unless recipe_already_blocked

    roulette
  end

  private

    def render_appropriate_page(list_of_recipe_names)
      if list_of_recipe_names.length > 0
        @recipe_name = list_of_recipe_names[0]
        render 'roulette'
      else
        render "sorry"
      end
    end

    def gather_user_recipe_names
      user_ingredients = current_user.pantry.ingredients # list of ingredient objects
      recipe_search_results = Set.new

      user_ingredients.each do |ingredient|
        matching_recipes = ingredient.recipes # each ingredient should be involved in one or more recipes
        recipe_search_results.merge(matching_recipes)
      end

      current_user.blockedrecipelist.recipes.each do |blocked_recipe|
        recipe_search_results.delete?(blocked_recipe)
      end

      # here, recipe_search_results is a list of relevant recipes
      list_of_recipe_names = recipe_search_results.map do |recipe|
        recipe.to_s
      end

      list_of_recipe_names # return list of recipe names
    end

end

app/controllers/users/confirmations_controller.rb
class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when omniauth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # You can put the params you want to permit in the empty array.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class User::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/users_helper.rb
module UsersHelper

  # For a given user, returns a list of ingredient objects that are active in the pantry
  # If no ingredients are active, will return all ingredients in pantry

  def get_active_ingredients(user)
    pantry = user.pantry
    pantry_ingredients = PantryIngredient.where(pantry_id: pantry.id, active: true)
    if pantry_ingredients.empty?
      pantry_ingredients = PantryIngredient.where(pantry_id: pantry.id)
    end

    active_ingredients = []
    pantry_ingredients.each do |pantry_ingredient|
      active_ingredients << Ingredient.find(pantry_ingredient.ingredient_id)
    end
    return active_ingredients
  end

  def percentage_of_ingredients_matched(recipe, user = current_user)
    num_of_ingredients_matched = (recipe.ingredients & get_active_ingredients(user)).length
    percent_of_ingredients_matched = num_of_ingredients_matched.fdiv(recipe.ingredients.length) * 100
  end

  # given a recipe, returns a percent of ingredients matched
  def progress_bar_percentage(recipe, user = current_user)
    percent_of_ingredients_matched = percentage_of_ingredients_matched(recipe, user)
    case percent_of_ingredients_matched
    when 0..10
      return "#A00000"
    when 10..20
      return "#FF0000"
    when 20..30
      return "#FF6600"
    when 30..40
      return "#FF9900"
    when 40..50
      return "#FFCC00"
    when 50..60
      return "#FFFF00"
    when 60..70
      return "#CCFF00"
    when 70..80
      return "#99FF00"  
    when 80..90
      return "#66CC00"
    else
      return "#339900"
    end
  end
end

app/views/users/_dashboardbuttons.js.erb
$(document).ready(function() {
  if (window.location.href.indexOf("/block/") > -1) {
    window.history.pushState("Dashboard", "Dashboard", "/users/dashboard");
  }
});

app/views/users/_pantry.html.erb
<ul>
  <% @pantry.ingredients.each do |ingredient| %>
    <li> <%= ingredient.name %> </li>
  <% end %>
</ul>

app/views/users/_roulettebuttons.js.erb
var recipe_index = 0;

var change_displayed_recipe = function(recipe_id) {
  $.post("/users/roulette", { "recipe_id": recipe_id }, function(data) {
      $(".outer-roulette").replaceWith(data);
    }, "html");
};

var block_displayed_recipe = function(recipe_id) {
  $.post("/users/block/" + recipe_id);
};

$(document).ready(function() {
  console.log(list_of_recipe_ids);

  var len_of_recipe_list = list_of_recipe_ids.length; // length should be at least one
  
  $("body").on("click", "#skip-button", function() {
    recipe_index = (recipe_index + 1) % len_of_recipe_list;
    change_displayed_recipe(list_of_recipe_ids[recipe_index]);
  });

  $("body").on("click", "#block-button", function() {
    block_displayed_recipe(list_of_recipe_ids[recipe_index]);
    list_of_recipe_ids.splice(recipe_index, 1);
    len_of_recipe_list = list_of_recipe_ids.length;
    if (len_of_recipe_list == 0) {
      change_displayed_recipe("None");
    } else {
      change_displayed_recipe(list_of_recipe_ids[recipe_index]);
    }
  });
});

app/views/users/_roulettelegend.html.erb
<div id="legendary">
  <div class="foo" style="width:10px; margin-left:0px; margin-right:20px; font-style:bold;">0%</div>
  <div class="foo" style="background-color:#A00000;"></div>
  <div class="foo" style="background-color:#FF0000;"></div>
  <div class="foo" style="background-color:#FF6600;"></div>
  <div class="foo" style="background-color:#FF9900;"></div>
  <div class="foo" style="background-color:#FFCC00;"></div>
  <div class="foo" style="background-color:#FFFF00;"></div>
  <div class="foo" style="background-color:#CCFF00;"></div>
  <div class="foo" style="background-color:#99FF00;"></div>
  <div class="foo" style="background-color:#66CC00;"></div>
  <div class="foo" style="background-color:#339900;"></div> 
  <div class="foo" style="margin-left:10px; margin-right:0px; width:40px; font-style:bold;">100%</div>
</div>

app/views/users/_roulettemain.html.erb
<div class="outer-roulette contain-center">

  <div id="block-button">
    <button class="btn" type="button">Block</button>
  </div>

  <div id="skip-button">
    <button label="skip" class="btn" type="button">Skip</button>
  </div>

  <div class="row" id="row1">
  
    <div class="roulette contain-center" style = "background-color:<%=progress_bar_percentage(@recipe)%>"=>
      <div id="recipe-name">
        <%= @recipe.name %>
      </div>

      <div id="roulette-picture">
        <% #Change "#{@recipe.name}.jpg" to "#{@recipe.img_url}" to support Imgur hosting %>
        <%= link_to (image_tag @recipe.image.url(:medium)), recipe_path(@recipe), :title => "View #{@recipe.name} recipe" %> 
      </div>
      
  </div> <!-- end of roulette -->

  </div> <!-- end of row1 -->

  <br>
  <div class="row contain-center legend">
    <%= render 'roulettelegend' %>
  </div>

</div>

app/views/users/_sorrymessage.html.erb
<span style="text-align:center"> <p>No matches found. Loosen your search criteria or add more ingredients to the pantry.<br> Recipes can be unblocked in the User Settings menu.</p></span>

app/views/users/dashboard.html.erb
<html>
  <div class="dashboard-header-big">
	<h1> <%= "Welcome to your dashboard, #{@user.email}!" %> </h1>
	</div>
	<div id="dashboard-pantry">
		<div class="dashboard-header-med">
		  <h2> Your Pantry </h2>
		</div>
		<% if flash[:ingredienterror] %>
			<div class="alert alert-warning text-center" role="alert">
        <span class="glyphicon glyphicon-warning-sign" aria-hidden="true"></span>
        <%= flash[:ingredienterror]%>
        <div class="col-md-7 col-md-offset-3">
          <%= button_to("Add", { action: 'update', controller: "pantries", commit: "Add New Ingredient", ingredient_name: params[:ingredient_name] }, method: :post, class: "btn btn-default btn-md col-md-5") %>
          <%= button_to "Nah", users_dashboard_path, {method: "get", class: "btn btn-default btn-md col-md-5"} %>
        </div>
        <p>&nbsp</p>
      </div>
		<% end %>

		<div class="add-ingredient">
      <% # This form should link to an update route to add ingredients %>
      <%= form_for(@pantry) do |i| %>
        <%= i.label :ingredient_name %> <br />
        <%= text_field_tag :ingredient_name, nil, placeholder: "ingredient",  data: {autocomplete_source: Ingredient.all.map(&:name)} %>
        <%= submit_tag "Add Ingredient" %>
      <% end %>
    </div>
		<div class="pantry-list">
      <%= form_tag({ controller: 'users', action: 'roulette' }, method: :post) do %>
  		  <ul id="ingredients" data-update-url="<%= sort_pantries_url%>">
    		<% @pantry.ingredients.sort_by {|a| a.pantry_ingredients[0].position}.each do |ingredient| %>
          <%= content_tag_for :li, ingredient do %>
        		<div class="pantry-ingredient">
          		<%= check_box_tag("pantry[ingredient_ids][]", ingredient.id, PantryIngredient.find_by(pantry_id: @pantry.id, ingredient_id: ingredient.id).active, id: dom_id(ingredient)) %>
          		<%= label_tag dom_id(ingredient), ingredient.name %>
          		<span class="remove-button">
              	<%= link_to("X", { action: 'update', controller: "pantries", commit: "Delete Ingredient", ingredient: ingredient.id }, style: 'color:red', method: :post) %>
            	</span>
        		</div>
          <% end -%>
    		<% end %>
  		</ul>
		</div>
	</div>

	<div id="dashboard-saved-recipes">
	  <div class="dashboard-header-med">
	    <h2> Your Saved Recipes </h2>
		</div>
		<%= render 'users/dashboard/savedrecipes' %>
	</div>

  <div id="dashboard-top-rated-recipes">
    <div class="dashboard-header-med">
      <h2> Top Rated Recipes </h2>
    </div>
    <%= render 'users/dashboard/topratedrecipes' %>
  </div>

  <div id="dashboard-filters">
    <h2> Recipe Filters </h2>
    <% Tag.all.each do |t| %>
      <span class="tag">
        <%= check_box_tag("tags[tag_ids][]", t.id, true, id: dom_id(t)) %>
        <%= label_tag dom_id(t), t.name %>
      </span>
    <% end %>
    <br>
    <div id ="prep-time-filter">
      <%= label_tag 'prep-time', 'Max prep time' %>
      <%= number_field_tag("max_prep_time", nil, in:0...10000, step:1, id: 'prep-time') %>
      <%= label_tag 'prep-time', 'minutes' %>
    </div>
    <div id ="cook-time-filter">
      <%= label_tag 'cook-time', 'Max cook time' %>
      <%= number_field_tag("max_cook_time", nil, in: 0...10000, step:1, id: 'cook-time') %>
      <%= label_tag 'cook-time', 'minutes' %>
    </div>
  </div>

	<div id="roulette-button">
    <%= submit_tag "Play Roulette", controller: :users, action: "roulette", method: :post, class: "btn btn-primary btn-lg" %>
    <% end %>
	</div>
</html>

<script type="text/javascript">
  <%= render 'dashboardbuttons.js' %>
</script>

app/views/users/roulette.html.erb
<% #@recipe is the instance variable passed to this view %>

<%= render 'roulettemain' %>

<script type="text/javascript">
  var list_of_recipe_ids = <%= raw @list_of_recipe_ids.to_json %>;
  <%= render 'roulettebuttons.js' %>
</script>

app/views/users/sorry.html.erb
<%= render 'sorrymessage' %>