config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => 'registrations' }
  root to: redirect('users/dashboard')
  get 'users/roulette' => 'users#dashboard'
  post 'users/roulette' => 'users#roulette'
  post 'users/block/:id' => 'users#block'
  post 'users/unblock' => 'users#unblock'
  post 'users/set_threshold' => 'users#set_threshold'
  post 'users/save/:id' => 'users#save'
  get 'users/unblock_all' => 'users#unblock_all'
  get  'users/dashboard' => 'users#dashboard'
  post 'users/dashboard' => 'users#update'
  post 'pantries/update' => 'pantries#update'
  post 'users/delete' => 'users#delete'
  resources :ratings, only: :update
  resources :recipes
  resources :pantries do
    collection {post :sort}
  end

end

app/views/layouts/_footer.html.erb
<footer>
  <center>
    <p> Developed by Nolan Chan, Anthony Kittiudom, Robinson Kuo, and Don Mai </p>
  </center>
</footer>

app/views/layouts/_header.html.erb
  <header class="navbar navbar-fixed-top header">
    <div class="container">
      <%= link_to "Recipe Roulette", root_path, method: :get, class: "logo" %>
      <nav>
        <ul class="nav navbar-nav pull-right">
          <% if user_signed_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><strong><%= current_user.email %></strong><span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to 'User Settings', edit_user_registration_path %></li>
                <li><li class="divider"></li></li>
                <li><%= link_to "Dashboard", users_dashboard_path, method: :get %></li>
                <li><%= link_to "Roulette", users_roulette_path, method: :post %></li>
                <li><%= link_to "Add New Recipe", new_recipe_path, method: :get %> </li>
                <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign up", new_user_registration_path %></li>
            <li><%= link_to "Login", new_user_session_path, id: "Login" %><li>
          <% end %>
        </ul>
      </nav>
    </div>
  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RecipeRoulette</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class='wrapper'>
    <%= render 'layouts/header' %>

    <div class="container mainbody">
      <% if flash[:notice]%>
        <div class="alert alert-success text-center" role="alert">
          <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
          <%= flash[:notice]%>
        </div>
      <% elsif flash[:alert] %>
        <div class="alert alert-danger text-center" role="alert">
          <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
          <%= flash[:alert]%>
        </div>
      <% end %>
      <%= yield %>
    </div>

  </div> <!-- end of wrapper -->
</body>
</html>